# Generated by Django 5.1.3 on 2026-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transaction_date_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.RenameField(
            model_name='historicalprice',
            old_name='date',
            new_name='priced_at',
        ),
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together={('asset', 'priced_at')},
        ),
    ]
