# Generated by Django 5.1.3

from django.db import migrations, models


def copy_asset_codes(apps, schema_editor):
    Transaction = apps.get_model('portfolio', 'Transaction')
    HistoricalPrice = apps.get_model('portfolio', 'HistoricalPrice')

    for row in Transaction.objects.all():
        row.asset_code = row.asset.code if row.asset_id else 'USD'
        row.save(update_fields=['asset_code'])

    for row in HistoricalPrice.objects.all():
        row.asset_code = row.asset.code if row.asset_id else 'USD'
        row.save(update_fields=['asset_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_datefields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='asset_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RunPython(copy_asset_codes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalprice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.RenameField(
            model_name='historicalprice',
            old_name='asset_code',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='asset_code',
            new_name='asset',
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='asset',
            field=models.CharField(
                choices=[('USD', 'US Dollar'), ('GA', 'Gram Gold')],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.CharField(
                choices=[('USD', 'US Dollar'), ('GA', 'Gram Gold')],
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together={('asset', 'date')},
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
