# Generated by Django 5.1.3 on 2026-08-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_asset_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='asset',
            field=models.CharField(choices=[('USD', 'ABD Doları'), ('GA', 'Gram altın')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.CharField(choices=[('USD', 'ABD Doları'), ('GA', 'Gram altın')], max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlyPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('asset_code', models.CharField(choices=[('USD', 'ABD Doları'), ('GA', 'Gram altın')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost_try', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_value_try', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pnl_try', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('year', 'month', 'asset_code')},
            },
        ),
    ]
